### ISSUE TITLE
Hash Mismatch

### ISSUE THREAD

**Issue by bc-ble** [ripclawffb/chocolatey-p4#5]
Hello,

It appears that this change broke installing p4 via chocolatey due to a hash mismatch. 

https://github.com/ripclawffb/chocolatey-p4/pull/4

We are seeing the same error in our build logs as the failure in that PR's CI run.

https://ci.appveyor.com/project/ripclawffb/chocolatey-p4/builds/49387227

<img width="1624" alt="image" src="https://github.com/ripclawffb/chocolatey-p4/assets/131190231/a0f6932a-b3a8-41c4-89e4-da3a8a1cf69a">

**Comment by ripclawffb** [comment]
Can you confirm what version you are installing? I just installed the latest 2023.2 package and it worked. If you are version pinning, you'll need to update to `2023.2.2563409`.

```
By installing, you accept licenses for the packages.
Progress: Downloading p4 2023.2.2563409... 100%

p4 v2023.2.2563409 [Approved]
p4 package files install completed. Performing other installation steps.
The package p4 wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): y

Downloading p4 64 bit
  from 'https://cdist2.perforce.com/perforce/r23.2/bin.ntx64/helix-p4-x64.exe'
Progress: 100% - Completed download of C:\Users\admin\AppData\Local\Temp\chocolatey\p4\2023.2.2563409\helix-p4-x64.exe (12.31 MB).
Download of helix-p4-x64.exe (12.31 MB) completed.
Hashes match.
Installing p4...
p4 has been installed.
  p4 may be able to be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of p4 was successful.
  Software installed to 'C:\Program Files\Perforce\'

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

**Comment by bc-ble** [comment]
We are just running `choco install -y --no-progress p4` and according to our build logs it's trying to install `2023.2.2563409`.

```09:05:41      build.amazon-ebs.windows: Progress: 100% - Completed download of C:\Users\Administrator\AppData\Local\Temp\chocolatey\p4\2023.2.2563409\helix-p4-x64.exe (12.29 MB).
09:05:41      build.amazon-ebs.windows: Download of helix-p4-x64.exe (12.29 MB) completed.
09:05:45      build.amazon-ebs.windows: Error - hashes do not match. Actual value was 'F49F5951BE69AE9618C094E089BC66B92A046DD7E42872F7E6F4CFD4328DAAF6'.
09:05:45      build.amazon-ebs.windows: ERROR: Checksum for 'C:\Users\Administrator\AppData\Local\Temp\chocolatey\p4\2023.2.2563409\helix-p4-x64.exe' did not meet '14a2cb53f28f49e61e409fdaee0af9f46607f8249b94d8aec077d1b4d25135c5' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
09:05:45      build.amazon-ebs.windows: The install of p4 was NOT successful.
09:05:45      build.amazon-ebs.windows: Error while running 'C:\ProgramData\chocolatey\lib\p4\tools\chocolateyinstall.ps1'.
```

That log snippet is from today around 9 AM Pacific but we've been seeing the failure for a couple of days.
In our CI the machines are fresh images based on the public Windows_Server-2022-English-Full-Base-2024.02.14 AMI so we don't have anything cached.

Interestingly I just tested this from a Windows 11 client and it was successful.

<img width="719" alt="image" src="https://github.com/ripclawffb/chocolatey-p4/assets/131190231/df6c3752-c8f2-405a-8140-f887d13c3039">

I can't think of a reason this would fail in CI but work interactively.

**Comment by ripclawffb** [comment]
I'm seeing similar failures in my CI as well. What's odd is that it worked in Chocolatey's validation pipeline. Perforce updates their helix binaries with the same name in place of the old ones and just updates the hash.

It looks like Perforce is using a CDN. I wonder if some of the locations are out of date. Let me reach out to Perforce and see if they can help investigate.

**Comment by bc-ble** [comment]
Thanks! Let me know if I can provide any more information.

If it's helpful our CI runs out of AWS's us-east-2 (Ohio) region and my working client is near AWS's us-west-2 (Oregon) region.

**Comment by ripclawffb** [comment]
I got in touch with support and they said they looked into it. I just re-ran the ci test and it passed. Can you try it now?

**Comment by bc-ble** [comment]
It's working for us again as well. Thanks for getting to the bottom of it!
