### ISSUE TITLE
Checksum issue

### ISSUE THREAD

**Issue by MariiaDzhenkova** [ripclawffb/chocolatey-p4#9]
Hi,

We have a problem with checksum during `choco install p4`.

`ERROR: Checksum for '2024.1.2596294\helix-p4-x64.exe' did not meet 'abf4757b946ce16b56d9e364ce8a28a99838f16283c3af15efc17676c3262b05' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.`

Could you provide a fix, please?

**Comment by ripclawffb** [comment]
Resolved with #10
